spring:
  application:
    name: EmailSenderWeb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CONFIRMATION_EMAIL}
    password: ${EMAIL_SECRET_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://mysql:3306/email_sender?createDatabaseIfNotExist=true # for local use set localhost instead of //mysql for docker use //mysql
    username: root
    password: ${DB_PASSWORD}
  data:
    redis:
      host: redis # host redis for docker, local for local development
      port: 6379
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET_KEY}
    accessTokenExpiration: 7200 # 2 hours
    refreshTokenExpiration: 604800 # 7 days
  token:
    encrypt: ${TOKEN_ENCRYPTION_KEY}


email:
  follow-up:
    quantity: 2 # maximum 2 follow up
    expiration: 48h
  scheduling:
    default-delay-seconds: 15 # 15 seconds

google:
  oauth2:
    client-id: ${GMAIL_CLIENT_ID}
    client-secret: ${GMAIL_CLIENT_SECRET}
    redirect-uri: http://localhost/oauth2callback
    scope: https://mail.google.com/
  smtp:
    host: smtp.gmail.com
    port: 587
    type: GMAIL

app:
  url: http://localhost:8080
  frontend-url: http://localhost
  frontend-login: http://localhost
